FROM node:14.4.0-alpine3.12

WORKDIR /app

# COPY ["package.json", "package-lock.json*", "."]
COPY package*.json ./

RUN npm install --silent
# RUN npm install react-scripts@3.4.1 -g --silent


COPY . .

CMD ["npm", "run", "start"]
