sudo: required
service:
  - docker

before_install:
  - docker build -t adiachan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adiachan/react-test npm test


after_success:
  - docker build -t adiachan/multi-client ./client
  - docker build -t adiachan/multi-nginx ./nginx
  - docker build -t adiachan/multi-server ./server
  - docker build -t adiachan/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adiachan/multi-client
  - docker push adiachan/multi-nginx
  - docker push adiachan/multi-server
  - docker push adiachan/multi-worker

